sudo: required
services:
- docker

before_install:
- docker build -t vivekvyasdeveloper/react-test -f ./client/Dockerfile.dev ./client

script:
- docker run -e CI=true vivekvyasdeveloper/react-test npm test

after_success:
- docker build -t vivekvyasdeveloper/multi-client ./client
- docker build -t vivekvyasdeveloper/multi-nginx ./nginx
- docker build -t vivekvyasdeveloper/multi-server ./server
- docker build -t vivekvyasdeveloper/multi-worker ./worker
